### ISSUE TITLE
Launching app error 

### ISSUE THREAD

**Issue by kk4sh** [sunkay/meteor-boiler#2]
Hi, i like to test your package but an error occurs on launching.

Here is the beginning of the error message 

```
/root/.meteor/packages/meteor-tool/.1.0.41.yumiah++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:206
throw(ex);
  ^
Error: ENOTDIR, open '/root/meteor-boiler-master/packages/tests-proxy/tests/cucumber/fixtures.js'
  at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.0.41.yumiah++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:326:15)
  at Object.wrapper [as readFile] (/root/.meteor/packages/meteor-tool/.1.0.41.yumiah++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/files.js:1124:24)
```

Any help ?

**Comment by sunkay** [comment]
looks like the cucumber tests.. 

BTW - are you using any cordova build at the moment? Since I see the error happening in the cordova build files....

**Comment by sunkay** [comment]
the ENOTDIR error states that the directory is not there. I think there might be some permissions issue...

Here is what you can try:
1. Clone the meteor-boiler from the git repository in a fresh directory
2. Run meteor command
3. Ignore any test errors that might happen
4. Go to localhost:3000 and see if the suntheme functionality is working

Report back and we can take it from there....

**Comment by kk4sh** [comment]
Hum ok. 
Unzipping the package affects the /tests directory . 
By fixing it, all runs.  
Thanks
